### ISSUE TITLE
Are you trying to mount a directory onto a file (or vice-versa)?

### ISSUE THREAD

**Issue by RomanL1** [daBONDi/go-rest-wol#10]
Got an error while executing command:
docker run -p 6969:8080 -v $(pwd)/externall-file-on-host.csv:/app/computer.csv dabondi/go-rest-wol
Error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/docker/wol/go-rest-wol/externall-file-on-host.csv\\\" to rootfs \\\"/var/lib/docker/overlay2/362ba73c41a6dbeec788a61feaf4eea29a9f34391d21808d3d0415bd6f88d1b2/merged\\\" at \\\"/var/lib/docker/overlay2/362ba73c41a6dbeec788a61feaf4eea29a9f34391d21808d3d0415bd6f88d1b2/merged/app/computer.csv\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by daBONDi** [comment]
Can you describe the problem what you mean a little bit better?

The Message you describe is from Docker itself, you need to mount the File to an existing file from Docker Commandline or whatever you use to spin the Container

You need to make sure the Path $(pwd)/externall-file-on-host.csv exists on your Docker Host

Have a look on Docker Manual about it: [https://docs.docker.com/storage/bind-mounts/](https://docs.docker.com/storage/bind-mounts/)

**Comment by RomanL1** [comment]
Sorry for my late Answer and my inaccurate Issue.
I was just installing and running everything and this issue happened.
Do you know what i can do about that?
I tried to change the path but it didn't work for me.

Kind Regards,
Roman Lysser

________________________________
Von: David Baumann <notifications@github.com>
Gesendet: Samstag, 28. März 2020 22:16
An: daBONDi/go-rest-wol <go-rest-wol@noreply.github.com>
Cc: Roman Lysser <Roman.Lysser@bbzsogr.ch>; Author <author@noreply.github.com>
Betreff: Re: [daBONDi/go-rest-wol] Are you trying to mount a directory onto a file (or vice-versa)? (#10)


Can you describe the problem what you mean a little bit better?

The Message you describe is from Docker itself, you need to mount the File to an existing file from Docker Commandline or whatever you use to spin the Container
