### ISSUE TITLE
Remote shutdown?

### ISSUE THREAD

**Issue by palla89** [daBONDi/go-rest-wol#11]
Hi!! Love your work! It works flawlessly!!

I know this request is not really an issue, but can we do something to remote shutdown also? I didn't find a nice solution and I think that wol doesn't support shutdown, but I've not found a real solution without installing some third party software on my windows pc. 
Do you have any advice?

**Comment by daBONDi** [comment]
for windows you cloud use winrm or wmi, but would be a cool feature 😁 remote shutdown

Am 04.04.2020 17:34 schrieb Alberto Paladino <notifications@github.com>:

Hi!! Love your work! It works flawlessly!!

I know this request is not really an issue, but can we do something to remote shutdown also? I didn't find a nice solution and I think that wol doesn't support shutdown, but I've not found a real solution without installing some third party software on my windows pc.
Do you have any advice?

**Comment by palla89** [comment]
I just tried the wmi thing and it worked!!! I just need to call from my Synology terminal this command: `net rpc shutdown -I ip-address -U user%password `
and it works! I don't know if it's a feature easily implementable in your docker image, but I'll try to play with it! Thank you again!!

**Comment by palla89** [comment]
Unfortunately, I don't know Go so it would take a lot for me, but I'd like to link this docker image that just adds the samba-common-bin , https://hub.docker.com/r/gableroux/debian-samba-common-bin maybe it could be "easy" to add to your project?

EDIT: Working on it!

**Comment by palla89** [comment]
After a long night (and thanks to the lockdown), I made a pull request for it!
