### ISSUE TITLE
Can't get work on Docker

### ISSUE THREAD

**Issue by daurpam** [daBONDi/go-rest-wol#16]
Really thank you for your work!

I'm trying to deploy your app into docker, with no success, well it was deployed successfully but can't get work. It seems that no magic packet was send.
Don't know it the problem is inside container or I have to configure some parameters in the host machine. 
I'm using 172.17.24.255:9 as broadcast IP, and tested with 172.17.24.254:9 too, none works.

Hope can help me!
Regards

**Comment by daBONDi** [comment]
You deploy the Container with Transperent Network?

Are the Clients in the same Layer 2 Networks as the Docker Container?

Because your Network Subnet looks like a Docker Internal Network

Am 13.07.2020 10:34 schrieb daurpam <notifications@github.com>:

Really thank you for your work!

I'm trying to deploy your app into docker, with no success, well it was deployed successfully but can't get work. It seems that no magic packet was send.
Don't know it the problem is inside container or I have to configure some parameters in the host machine.
I'm using 172.17.24.255:9 as broadcast IP, and tested with 172.17.24.254:9 too, none works.

Hope can help me!
Regards

**Comment by daurpam** [comment]
Thanks, for your answer.

Our subnet is private and the segment is 172.17.24.0/24. The docker container of WoL is on 172.18.0.0/24 when it's started. Don't know if perhaps it could be conflict between those networks, but it shouldn't.

**Comment by xgonc** [comment]
@daurpam I'm having the same problem. I have `go-rest-wol` in a docker container (set up using docker compose) and a traefik router.
The `go-rest-wol` has access to both internal and host networks, but still I don't have any magic packets outside the host.
Did you solve your issue? Do you have a workaround? 
Thanks

**Comment by daurpam** [comment]
> Did you solve your issue? Do you have a workaround?

sorry but not find any solution.. I still looking why the magic packet isn't send to the lan. I thought that perhaps docker image need some component on Dockerfile, but I'm not an experienced user with Docker.

**Comment by daurpam** [comment]
@daBONDi 
I have checked all from the beginning, And could be the problem that I'm using Linux as Host and doesn't have **transparent network** for config in docker?

**Comment by daBONDi** [comment]
Try "host" network configuration.

https://docs.docker.com/network/network-tutorial-host/

Use Wireshark on a client in the same network to check if the wol packets hitting the client network.

when a router ia between the desires network you need to define a unicast destination also in the computer Config file, normaly routers gateway address of the desires client network and your router need to forward also the wol pakets

Thats not a problem of the Container or software more a problem a correctly configured Network/Router


Am 27.07.2020 07:50 schrieb daurpam <notifications@github.com>:

@daBONDi<https://github.com/daBONDi>
I have checked all from the beginning, And could be the problem that I'm using Linux as Host and doesn't have transparent network for config in docker?

**Comment by daurpam** [comment]
Unfortunately **transparent** option for network isn't available for Linux host. I have to create a **macvlan** network to get work the docker.  This is an example:
#create network on docker
`docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=ens12 net_mac`

#assign created network to container
`docker run --network net_mac --ip=192.168.1.250 dabondi/go-rest-wol`

Be careful with the IP associated to the container, to avoid conflicts with another devices on lan.

Thanks @daBONDi

**Comment by daBONDi** [comment]
> Unfortunately **transparent** option for network isn't available for Linux host. I have to create a **macvlan** network to get work the docker. This is an example:
> #create network on docker
> `docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=ens12 net_mac`
> 
> #assign created network to container
> `docker run --network net_mac --ip=192.168.1.250 dabondi/go-rest-wol`
> 
> Be careful with the IP associated to the container, to avoid conflicts with another devices on lan.
> 
> Thanks @daBONDi

Its the same as Transperent Network under Windows, dont know its named that on Linux, damn Microsoft Marketing department  😁.

Awesome that you got it Working maybe make a Pr with an example and description for linux in the README.md ,would be awesome!
