### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JamesDAdams** [daBONDi/go-rest-wol#17]
works for a few minutes and then doesn't work at all

**Comment by daBONDi** [comment]
Without more information there is nothing we can do about it.

**When it is not working:**
- The Container runs?
- The Container is in Transperent Network Mode?
- You don't see WOL Packages when Sniffing the Docker Servers network interface?
- What Version you run?
- What Docker Server you run?
- Do you run in a NAS?
- Some Container Logs?
- Crash the Container?

_Without a little work from you there we be no help, you whine about it without knowing anything_
