### ISSUE TITLE
Dockerhub?

### ISSUE THREAD

**Issue by vrokolos** [daBONDi/go-rest-wol#3]
Can you add this to docker hub?

**Comment by daBONDi** [comment]
Will do, but will take awhile to find a work window for it, sorry :-(

**Comment by daBONDi** [comment]
I integrated with dockerhub and build on docker currently.

**Docker Image:** dabondi/go-rest-wol

Hope this satisfy your current needs.

PS.: Maybe i will rebuild it with travis but in the meantime it should work

**Comment by vrokolos** [comment]
Thanks!
