### ISSUE TITLE
Readme typo: false docker image

### ISSUE THREAD

**Issue by Prophet96ix** [daBONDi/go-rest-wol#8]
Hi,
the Readme is wrong and has a typo.

It says: Docker Image: dabondi/get-rest-wol
Correct would be: Docker Image: dabondi/go-rest-wol

Hope somebody will fix that :)

**Comment by daBONDi** [comment]
Will do 😁 when find time tonight 😄

**Comment by Prophet96ix** [comment]
Alright, thank you :)
If I figure out how to create a MR I can do that, too

**Comment by daBONDi** [comment]
Fixed :-)

**Comment by Prophet96ix** [comment]
nice :) thx
