### ISSUE TITLE
Port from environment

### ISSUE THREAD

**Issue by ADIX7** [daBONDi/go-rest-wol#9]
Can you add an option to set http port environment variable? I use it in docker but I have to set 'network_mode: host'. But I use 8080 for an other service.

**Comment by daBONDi** [comment]
Sry for take so long will trY to get it done this week

**Comment by daBONDi** [comment]
Sorry, Corona Virus/Work hold me on so long :-) I made the changes and hopefully not destroy any other thing :-)

User **WOLHTTPPORT** to setup the port the process will use.

**Comment by ADIX7** [comment]
Thanks!! It's working perfectly! :) Awesome app!
